openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: API для управления контактами с аутентификацией и авторизацией
tags:
  - name: Contacts
    description: Операции с контактами
servers:
  - url: http://localhost:3000
  - url: https://nodejs-hw-mongodb-vcmd.onrender.com
paths:
  /contacts:
    get:
      $ref: '../swagger/paths/contacts/get.yaml'
    post:
      $ref: '../swagger/paths/contacts/post.yaml'
  /contacts/{contactId}:
    get:
      $ref: '../swagger/paths/contacts/{id}/get.yaml'
    patch:
      $ref: '../swagger/paths/contacts/{id}/patch.yaml'
    delete:
      $ref: '../swagger/paths/contacts/{id}/delete.yaml'
components:
  schemas:
    Contact:
      $ref: '../swagger/components/schemas.yaml#/Contact'
    PaginationInfo:
      $ref: '../swagger/components/schemas.yaml#/PaginationInfo'
  responses:
    NotFound:
      $ref: '../swagger/components/responses.yaml#/NotFound'
    Unauthorized:
      $ref: '../swagger/components/responses.yaml#/Unauthorized'
    BadRequest:
      $ref: '../swagger/components/responses.yaml#/BadRequest'
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
